### ISSUE TITLE
Support Alamofire 4

### ISSUE THREAD

**Issue by Beniamiiin** [jankaltoun/AlamofireEasyLogger#4]
Hi, @jankaltoun. We use Alamofire 4 on our project. I can send a pull request with these changes and you can store it in a separate branch. What do you think about it? Maybe for someone, it will be useful too.

**Comment by jankaltoun** [comment]
That's a good point 🙂.

I prepared this branch: https://github.com/jankaltoun/AlamofireEasyLogger/tree/alamofire-4-carthage

Can you give it a shot?

**Comment by Beniamiiin** [comment]
So, I just can use this branch, can't I?

**Comment by jankaltoun** [comment]
Yup, I’ll keep it around 🙂.

**Comment by Beniamiiin** [comment]
Thanks 🙂
