### ISSUE TITLE
AlamofireLogger is not open

### ISSUE THREAD

**Issue by tonnylitao** [jankaltoun/AlamofireEasyLogger#5]
try to custom logger using AlamofireLoggerDelegate, but

'AlamofireLogger' initializer is inaccessible due to 'internal' protection level

**Comment by jankaltoun** [comment]
Hi @tonnylitao ! Great catch 🙂 .
I just released a new version `1.4.0` with a fix. Can you please try that one?

**Comment by Khislatjon** [comment]
@jankaltoun Very useful library. Thank you!

**Comment by jankaltoun** [comment]
@Khislatjon I'm glad you like it! 🙂
