### ISSUE TITLE
can't access struct values 

### ISSUE THREAD

**Issue by johnqinheracles** [jankaltoun/AlamofireEasyLogger#6]
cannot access properties in AlamofireLoggerRequest in AlamofireLoggerDelegate implementation.
FancyAppAlamofireLogger doesn't have this issue because it is still within the package. if you try to implement AlamofireLoggerDelegate in the example project, you will encounter the same issue.
 
https://stackoverflow.com/questions/54673224/public-struct-in-framework-init-is-inaccessible-due-to-internal-protection-lev

Pull Request: https://github.com/jankaltoun/AlamofireEasyLogger/pull/7

**Comment by jankaltoun** [comment]
Hi @johnqinheracles ! I'm sorry for the belated reply.
I just merged your PR, good job! Thank you for creating it, I very much appreciated that! 🙂
